### ISSUE TITLE
Write basic tests

### ISSUE THREAD

**Issue by 1ndy** [EnzymeFunctionInitiative/EST#20]
Write basic tests that test the creation of parameter files under different import modes. These should not be designed to test edge cases but rather confirm that no changes have caused regressions.

- [ ] Add option to specify which config to use

**Comment by nilsoberg** [comment]
`--blast-query smalldata/blast_query.fa` can be added to `create_est_nextflow_params.py` line in `est_sequence_blast.sh` to support BLAST input option.

A sequence for testing can be extracted from the small dataset:

`perl -e '$h=0; while (<>) { last if (m/^>/ and ++$h > 1); next if m/^>/; $seq .= $_; } print $seq;' < smalldata/test.fasta > smalldata/blast_query.fa`
