### ISSUE TITLE
Relocate nextflow work and log outputs in test

### ISSUE THREAD

**Issue by 1ndy** [EnzymeFunctionInitiative/EST#64]
Each pipeline in the repo has a test in `tests/modules`. A module is simply a bash script which generate parameters and executes nextflow. However, the current `nextlfow run...` command does not specify where to store work and logs, and so the default `work/` and `.nextflow.log` are used. This pollutes the repository root and makes it difficult to investigate a failing test.

For each module in `tests/modules`:
- [x] Use the `-log` nextflow option to output the log file in the directory where results are stored for the pipeline
- [x] Use the `-work-dir` option on the `run` subcommand to ensure that the `work` directory is co-located with the results

More information on Nextflow CLI options can be found [here](https://www.nextflow.io/docs/latest/cli.html).

**Comment by rbdavid** [comment]
Things to consider (in addition to hardcoding new locations for the files): 
- add commands to `make clean` that removes these files. Develop a `tests-clean` process that is called within the `clean` process.
- add `work/`, `.nextflow.log*` files, `test_results/` (really, the relocated dirs/files) to the .gitignore. Just as a backup for when we don't run the `make clean` command while committing.

**Comment by rbdavid** [comment]
Conversing with Nils, maybe these nextflow directories/files get written to `/tmp` file space so that they are written/stored outside of the repo. If errors occur, nextflow will point to those files all the same. 

This would avoid the `.gitignore` suggestion made above. Also, the `make tests-clean` would be low priority to run since the to-be-cleaned files would be in a temporary file space anyways. 

Only rationale for not doing this would be possibility of clashes in file and/or directory names in the `/tmp` space causing other processes to crash. Will need to test to see if this is an actual potential problem or just a figment.

**Comment by rbdavid** [comment]
Nextflow log files as well as results and work directories are now being written to a `/tmp/` directory space. 

The location of the `.nextflow/` directory [cannot be changed easily](https://stackoverflow.com/questions/70083511/change-the-location-of-the-nextflow-folder). It is always located in the working directory, where the nextflow command was called. Currently, the `Makefile`, `runtests.sh`, and module files all assume that the working directory is the EST repo home directory. So either we change those files to be more dynamic about where the working directory is or we include some post-test cleaning to `runtests.sh` (and in the Makefile as alluded to in messages above).

**Comment by nilsoberg** [comment]
In reviewing the changes in PR #95 it seems the approach recommended by @nilsoberg is flawed for several reasons:

1. the test data location is hard coded and relies on the existence of the `/tmp` directory.
2. makes unnecessary changes to the test module scripts and `runtests.sh` script
3. changes the meaning of the `$TEST_RESULTS_DIR` environment variable
4. running a `make` command that works on an external hard-coded directory seems like a bad practice
