### ISSUE TITLE
test file does not exist

### ISSUE THREAD

**Issue by Sunysh** [EnzymeFunctionInitiative/EST#93]
I am trying to test, but the following error occurs. How should I resolve it?
![WX20241011-152436](https://github.com/user-attachments/assets/35d5c979-b3c3-4f90-9102-0de14d2db585)

**Comment by nilsoberg** [comment]
There were some files renamed locally that were not renamed on the remote test dataset and that has been addressed.  I also updated the documentation in `docs/source/guides/testing.sh` to reflect the changes that have been made recently.  Please checkout branch `93-test-file-does-not-exist`, `rm -rf tests/test_data/smalldata`, and run `bash tests/runtests.sh test.singularity.config` again.  Following the guide in the updated testing document should also fix issue #92.  Let me know if this completes successfully and I will merge the changes into the main branch and close this issue.
